from discord import app_commands
from discord.ext import commands
import discord
import utils


class AiCog(commands.Cog):
    def __init__(self, bot):
        self.bot: commands.Bot = bot
        self.message = """It is recommended that you don't use AI agents for multiple reasons:
```1) Code generated by AI does not work. Most AI agents were not trained with enough Skript data so the code they generate frequently includes syntax from other languages (like Python) or invents syntax that doesn’t exist.

2) Blindly trusting code from any source is a bad idea, especially on production servers. Even if the code that was generated appears to work, you have no clue what vulnerabilities it introduces or fails to protect against.

3) Using AI to write your code takes away from your learning and doesn't challenge you to develop problem solving skills.```
While AI can be used as a tool, it is necessary to understand what it is doing and check any code it creates. Since this is a learning community, we want to support your personal growth. As a result, we don't allow generated content in our help channels ([Rule 8](<https://discord.com/channels/135877399391764480/224289277100425216/1071159546371911710>))"""

    @app_commands.command(description="Explain why it's a bad idea to use AI for Skript")
    @app_commands.describe(reply_to="The user you want to send this message to")
    @app_commands.allowed_installs(guilds=True, users=True)
    @app_commands.allowed_contexts(guilds=True, dms=True, private_channels=True)
    async def ai(self, interaction: discord.Interaction, reply_to: discord.User = None) -> None:
        await utils.send(
            interaction=interaction,
            content=self.message,
            ping=reply_to
        )


async def setup(bot):
    await bot.add_cog(AiCog(bot=bot))
